language: java
jdk:
    - openjdk10
    - openjdk12

cache:
    directories:
        - .git/lfs
git:
    lfs_skip_smudge: true

install:
    - git lfs pull

before_install:
    - sudo apt-get install jq
    - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar
    - grep -v '^#' assets/src/main/resources/META-INF/services/bisq.asset.Asset | sort --check --dictionary-order --ignore-case

script:
    - ./gradlew clean check codeCoverageReport

after_success:
    - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/codeCoverageReport.xml

notifications:
    slack:
        on_success: change
        on_failure: always
        rooms:
            -   secure: EzlqWTBuhb3FCfApjUXaShWgsWOVDwMXI7ISMiVBkcl2VFISYs/lc/7Qjr7rdy4iqQOQXMcUPHdwMUp0diX+GxiSjLARjUpKIvNOPswZWBL+3Z1h28jyOwtHRviZbM1EU0BZROrr+ODyTNz2lf+L1iXTkpSvk50o5JAnAkumsPw=
